Create :

INSERT INTO DAFTAR_MAHASISWA (nim, nama, alamat, nohp)

VALUES('20180801360', 'Nur Afalah ', ' talaga sari', '089658094632')

;

INSERT INTO DAFTAR_MAHASISWA (nim, nama, alamat, nohp)

VALUES('20180801310', 'Rizki Faro Khatiningsih', 'Panongan', '085758094632');



INSERT INTO DAFTAR_MAHASISWA (nim, nama, alamat, nohp)

VALUES('20180801382', 'Arnea Wanda Izzi', 'Gading', '081345678')
;

INSERT INTO DAFTAR_MAHASISWA (nim, nama, alamat, nohp)

VALUES('20180801317', 'Ade Lita', 'Legok', '0893245');



INSERT INTO DAFTAR_MAHASISWA (nim, nama, alamat, nohp)

VALUES('20160801323', 'Toni Ajeke', 'Cikupa', '08964321');



READ :

SELECT * FROM DAFTAR_MAHASIWA


SELECT * FROM DAFTAR_MAHASIWA
WHERE Nim = '20180801360'

SELECT * FROM DAFTAR_MAHASIWA
WHERE Nama = 'Nur Afalah'

UPDATE:
UPDET DAFTAR_MAHASISWA
SET alamat = 'Jl.talaga sari'
WHERE Nim = '20180801360'

DELETE :
DELETE FROM DAFTAR_MAHASISWA
WHERE nim ='20190801360'

=================================================================================================
CREATE :

INSERT INTO DAFTAR-DOSEN (nind, nama, alamat, nohp)

VALUES('20180801360', 'MAZMUR TARIGAN ', ' talaga sari', '089658094632')

;

INSERT INTO DAFTAR_DOSEN (nind, nama, alamat, nohp)

VALUES('20180801310', 'MARZUKI SILALHI', 'Panongan', '085758094632');



INSERT INTO DAFTAR_DOSEN (nind, nama, alamat, nohp)

VALUES('20180801382', 'M BAHRUL ULUM', 'Gading', '081345678')
;

INSERT INTO DAFTAR_DOSEN(nind, nama, alamat, nohp)

VALUES('20180801317', 'SYAHRIAL SYAHBANI', 'Legok', '0893245');



INSERT INTO DAFTAR_DOSEN(nind, nama, alamat, nohp)

VALUES('20160801323', 'NIA PUSPITASARI', 'Cikupa', '08964321');



READ :

SELECT * FROM DAFTAR_DOSEN


SELECT * FROM DAFTAR_DOSEN
WHERE Nim = '20180801360'

SELECT * FROM DAFTAR_DOSEN
WHERE Nama = 'MAZMUR TARIGAN'

UPDATE:
UPDET DAFTAR_DOSEN
SET alamat = 'CITRA'
WHERE Nim = '20180801360'

DELETE :
DELETE FROM DAFTAR_DOSEN
WHERE nim ='20190801360'

=================================================================================================

CREATE :

INSERT INTO DAFTAR_MATA_KULIYAH 

VALUES('CR1', 'BASIS DATA', '2', 'ILMU KOMPUTER')

;

INSERT INTO DAFTAR_MATA_KULIYAH 
VALUES('CR2', 'KALKULUS 2', '2', 'ILMU KOMUNIKASI');


INSERT INTO DAFTAR_MATA_KULIYAH 
VALUES('CR3', 'SISTEM OPERASI', '3', 'ILMU MATEMATIKA')
;

INSERT INTO DAFTAR_MATA_KULIYAH 
VALUES('CR4', 'PENDIDIKAN PANCASILA', '3', 'ILMU PENGETAHUAN ALAM');



INSERT INTO DAFTAR_MATA_KULIYAH 
VALUES('CR5', 'PENDIDIKAN KEWARGANEGARAAN', '2', 'ILMU BAHASA');



READ :

SELECT * FROM DAFTAR_MATA_KULIYAH


SELECT * FROM DAFTAR_MATA_KULIYAH
WHERE KDID = 'CR1'

SELECT * FROM DAFTAR_MATA_KULIYAH
WHERE Nama = 'BASIS DATA'

UPDATE:
UPDET DAFTAR_MATA_KULIYAH
SET SKS = '4'
WHERE KDID = 'CR1'

DELETE :
DELETE FROM DAFTAR_MATA_KULIYAH
WHERE KDID ='CR1'