DI BAWAH INI ADALAH BEBERAPA PERINTAH/QUERY YANG DITUGASKAN, NOTE : YANG TIDAK DIJALANKAN SAYA BERI KOMENTAR //
//QUERY CRUD (CREATE-READ-UPDATE-DELETE) ENTITY MAHASISWA

//QUERY CREATE UNTUK MENAMBAHKAN DATA KE DALAM TABEL

INSERT INTO 7_MAHASISWA
VALUES ('018080138','ARNEA WANDA IZZI','JEPANG','089660039065')
INSERT INTO 7_MAHASISWA
VALUES ('0180801360','NURAFALAH','AMERIKA','089660039066')
INSERT INTO 7_MAHASISWA
VALUES ('0180801317','ADELITA','INDIA','089660039067')
INSERT INTO 7_MAHASISWA
VALUES ('0180801310','RIZKI FARO K','KOREA','089660039068')
INSERT INTO 7_MAHASISWA
VALUES ('018080134','LARAS','INGGRIS','089660039069')
INSERT INTO 7_MAHASISWA
VALUES ('019080138','YULIUS','INDONESIA','089660039070')

//QUERY CREATE UNTUK MENAMBAHKAN DATA TERTENTU KE DALAM TABEL

INSERT INTO 7_MAHASISWA ([NIM],[NAMA])
VALUES ('018080138','ARNEA WANDA IZZI')
--------------------------------------------------------------
//QUERY READ UNTUK MENAMPILKAN DATA DALAM TABEL

//MENAMPILKAN SEMUA DATA TANPA KONDISI
SELECT * FROM 7_MAHASISWA

//MENAMPILKAN DATA DENGAN KONDISI NIM
SELECT * FROM 7_MAHASISWA
WHERE NIM = '018080138'

//MENAMPILKAN DATA DENGAN KONDISI NAMA
SELECT * FROM 7_MAHASISWA
WHERE NAMA = 'ARNEA WANDA IZZI'

//MENAMPILKAN DATA DENGAN KONDISI ALAMAT
SELECT * FROM 7_MAHASISWA
WHERE ALAMAT = 'JEPANG'

//MENAMPILKAN DATA DENGAN KONDISI NOHP
SELECT * FROM 7_MAHASISWA
WHERE NOHP = '089660039065'
------------------------------------------------------------------
//QUERY UPDATE UNTUK MENGUBAH DATA DALAM TABEL

//MENGUBAH SEMUA DATA ALAMAT TANPA KONDISI
UPDATE 7_MAHASISWA
SET ALAMAT = 'PAKISTAN' //TIDAK DIJALANKAN DALAM DB ORACLE

//MENGUBAH DATA ALAMAT DENGAN KONDISI NIM
UPDATE 7_MAHASISWA
SET ALAMAT = 'PAKISTAN'
WHERE NIM = '018080138'

//MENGUBAH DATA ALAMAT DENGAN KONDISI NAMA
UPDATE 7_MAHASISWA
SET ALAMAT = 'PAKISTAN'
WHERE NAMA = 'ARNEA WANDA IZZI' //TIDAK DIJALANKAN DALAM DB ORACLE

//MENGUBAH DATA ALAMAT DENGAN KONDISI ALAMAT
UPDATE 7_MAHASISWA
SET ALAMAT = 'PAKISTAN'
WHERE ALAMAT = 'JEPANG' //TIDAK DIJALANKAN DALAM DB ORACLE

//MENGUBAH DATA ALAMAT DENGAN KONDISI NOHP
UPDATE 7_MAHASISWA
SET ALAMAT = 'PAKISTAN'
WHERE NOHP = '089660039065' //TIDAK DIJALANKAN DALAM DB ORACLE
--------------------------------------------------------------------
//QUERY DELETE UNTUK MENGHAPUS DATA DALAM TABEL

//MENGHAPUS SEMUA DATA TANPA KONDISI
DELETE FROM 7_MAHASISWA //TIDAK DIJALANKAN DALAM DB ORACLE

//MENGHAPUS DATA DENGAN KONDISI NIM
DELETE FROM 7_MAHASISWA
WHERE NIM = '019080138'

//MENGHAPUS DATA DENGAN KONDISI NAMA
DELETE FROM 7_MAHASISWA 
WHERE NAMA = 'YULIUS' //TIDAK DIJALANKAN DALAM DB ORACLE

//MENGHAPUS DATA DENGAN KONDISI ALAMAT
DELETE FROM 7_MAHASISWA
WHERE ALAMAT = 'INDONESIA' //TIDAK DIJALANKAN DALAM DB ORACLE

/MENGHAPUS DATA DENGAN KONDISI NOHP
DELETE FROM 7_MAHASISWA 
WHERE NOHP = '089660039070' //TIDAK DIJALANKAN DALAM DB ORACLE

//////////////////////////////////////////////////////////////

DI BAWAH INI ADALAH BEBERAPA PERINTAH/QUERY YANG DITUGASKAN, NOTE : YANG TIDAK DIJALANKAN SAYA BERI KOMENTAR //
//QUERY CRUD (CREATE-READ-UPDATE-DELETE) ENTITY DOSEN

//QUERY CREATE UNTUK MENAMBAHKAN DATA KE DALAM TABEL
INSERT INTO 7_DOSEN
VALUES ('1719080138','MARZUKI SILALAHI','JEPANG','081311168869')
INSERT INTO 7_DOSEN
VALUES ('17190801360','M BAHRUL ULUM','AMERIKA','081311168870')
INSERT INTO 7_DOSEN
VALUES ('17190801317','SYAHRIAL SYAHBANI','INDIA','0813111688671')
INSERT INTO 7_DOSEN
VALUES ('17190801310','MASMUR TARIGAN','KOREA','08131116887')
INSERT INTO 7_DOSEN
VALUES ('1719080134','NIA PUSPITASARI','INGGRIS','081311168873')
INSERT INTO 7_DOSEN
VALUES ('1719080139','ERMAN ANOM','INDONESIA','081311168874')

//QUERY CREATE UNTUK MENAMBAHKAN DATA TERTENTU KE DALAM TABEL

INSERT INTO 7_DOSEN ([NID],[NAMA])
VALUES ('1719080138','MARZUKI SILALAHI')
--------------------------------------------------------------
//QUERY READ UNTUK MENAMPILKAN DATA DALAM TABEL

//MENAMPILKAN SEMUA DATA TANPA KONDISI
SELECT * FROM 7_DOSEN

//MENAMPILKAN DATA DENGAN KONDISI NID
SELECT * FROM 7_DOSEN
WHERE NID = '1719080138'

//MENAMPILKAN DATA DENGAN KONDISI NAMA
SELECT * FROM 7_DOSEN
WHERE NAMA = 'MARZUKI SILALAHI'

//MENAMPILKAN DATA DENGAN KONDISI ALAMAT
SELECT * FROM 7_DOSEN
WHERE ALAMAT = 'JEPANG'

//MENAMPILKAN DATA DENGAN KONDISI NOHP
SELECT * FROM 7_DOSEN
WHERE NOHP = '081311168869'
------------------------------------------------------------------
//QUERY UPDATE UNTUK MENGUBAH DATA DALAM TABEL

//MENGUBAH SEMUA ALAMAT DATA TANPA KONDISI
UPDATE 7_DOSEN
SET ALAMAT = 'PAKISTAN' //TIDAK DIJALANKAN DALAM DB ORACLE

//MENGUBAH DATA ALAMAT DENGAN KONDISI NID
UPDATE 7_DOSEN
SET ALAMAT = 'PAKISTAN'
WHERE NID = '1719080138'

//MENGUBAH DATA ALAMAT DENGAN KONDISI NAMA
UPDATE 7_DOSEN
SET ALAMAT = 'PAKISTAN'
WHERE NAMA = 'MARZUKI SILALAHI' //TIDAK DIJALANKAN DALAM DB ORACLE

//MENGUBAH DATA ALAMAT DENGAN KONDISI ALAMAT
UPDATE 7_DOSEN
SET ALAMAT = 'PAKISTAN'
WHERE ALAMAT = 'JEPANG' //TIDAK DIJALANKAN DALAM DB ORACLE

//MENGUBAH DATA ALAMAT DENGAN KONDISI NOHP
UPDATE 7_DOSEN
SET ALAMAT = 'PAKISTAN'
WHERE NOHP = '081311168869' //TIDAK DIJALANKAN DALAM DB ORACLE
--------------------------------------------------------------------
//QUERY DELETE UNTUK MENGHAPUS DATA DALAM TABEL

//MENGHAPUS SEMUA DATA TANPA KONDISI
DELETE FROM 7_DOSEN //TIDAK DIJALANKAN DALAM DB ORACLE

//MENGHAPUS DATA DENGAN KONDISI NID
DELETE FROM 7_DOSEN
WHERE NID = '1719080139'

//MENGHAPUS DATA DENGAN KONDISI NAMA
DELETE FROM 7_DOSEN 
WHERE NAMA = 'ERMAN ANOM' //TIDAK DIJALANKAN DALAM DB ORACLE

//MENGHAPUS DATA DENGAN KONDISI ALAMAT
DELETE FROM 7_DOSEN
WHERE ALAMAT = 'INDONESIA' //TIDAK DIJALANKAN DALAM DB ORACLE

/MENGHAPUS DATA DENGAN KONDISI NOHP
DELETE FROM 7_DOSEN 
WHERE NOHP = '081311168874' //TIDAK DIJALANKAN DALAM DB ORACLE

//////////////////////////////////////////////////////////////

DI BAWAH INI ADALAH BEBERAPA PERINTAH/QUERY YANG DITUGASKAN, NOTE : YANG TIDAK DIJALANKAN SAYA BERI KOMENTAR //
//QUERY CRUD (CREATE-READ-UPDATE-DELETE) ENTITY MATKUL

//QUERY CREATE UNTUK MENAMBAHKAN DATA KE DALAM TABEL

INSERT INTO 7_MATKUL
VALUES ('CR1','BAHASA INDONESIA','4','ILMU KOMUNIKASI')
INSERT INTO 7_MATKUL
VALUES ('CR','KALKULUS ','4','ILMU PENDIDIKAN')
INSERT INTO 7_MATKUL
VALUES ('CR3','PENDIDIKAN KEWARGANEGARAAN','','ILMU KEDOKTERAN')
INSERT INTO 7_MATKUL
VALUES ('CR4','PENDIDIKAN PANCASILA','4','ILMU MATEMATIKA')
INSERT INTO 7_MATKUL
VALUES ('CR5','SISTEM INFORMASI','','ILMU PENDIDIKAN ALAM')
INSERT INTO 7_MATKUL
VALUES ('CR6','MOTIVASI USAHA','4','ILMU KOMPUTER')

//QUERY CREATE UNTUK MENAMBAHKAN DATA TERTENTU KE DALAM TABEL
INSERT INTO ([KDID],[NAMA])
VALUES ('CR1','BAHASA INDONESIA')
--------------------------------------------------------------
//QUERY READ UNTUK MENAMPILKAN DATA DALAM TABEL

//MENAMPILKAN SEMUA DATA TANPA KONDISI
SELECT * FROM 7_MATKUL

//MENAMPILKAN DATA DENGAN KONDISI KDID
SELECT * FROM 7_MATKUL
WHERE KDID = 'CR1'

//MENAMPILKAN DATA DENGAN KONDISI NAMA
SELECT * FROM 7_MATKUL
WHERE NAMA = 'BAHASA INDONESIA'

//MENAMPILKAN DATA DENGAN KONDISI SKS
SELECT * FROM 7_MATKUL
WHERE SKS = '4'

//MENAMPILKAN DATA DENGAN KONDISI FAKULTAS
SELECT * FROM 7_MATKUL
WHERE FAKULTAS = 'ILMU KOMUNIKASI'
------------------------------------------------------------------
//QUERY UPDATE UNTUK MENGUBAH DATA DALAM TABEL

//MENGUBAH SEMUA SKS DATA TANPA KONDISI
UPDATE 7_MATKUL
SET SKS = '3' //TIDAK DIJALANKAN DALAM DB ORACLE

//MENGUBAH DATA SKS DENGAN KONDISI KDID
UPDATE 7_MATKUL
SET SKS = '3'
WHERE KDID = 'CR1'

//MENGUBAH DATA SKS DENGAN KONDISI NAMA
UPDATE 7_MATKUL
SET SKS = '3'
WHERE NAMA = 'BAHASA INDONESIA' //TIDAK DIJALANKAN DALAM DB ORACLE

//MENGUBAH DATA SKS DENGAN KONDISI SKS
UPDATE 7_MATKUL
SET SKS = '3'
WHERE SKS = '4' //TIDAK DIJALANKAN DALAM DB ORACLE

//MENGUBAH DATA SKS DENGAN KONDISI FAKULTAS
UPDATE 7_MATKUL
SET SKS = '3'
WHERE FAKULTAS = 'ILMU KOMUNIKASI' //TIDAK DIJALANKAN DALAM DB ORACLE
--------------------------------------------------------------------
//QUERY DELETE UNTUK MENGHAPUS DATA DALAM TABEL

//MENGHAPUS SEMUA DATA TANPA KONDISI
DELETE FROM 7_MATKUL //TIDAK DIJALANKAN DALAM DB ORACLE

//MENGHAPUS DATA DENGAN KONDISI KDID
DELETE FROM 7_MATKUL
WHERE NID = '1719080139'

//MENGHAPUS DATA DENGAN KONDISI NAMA
DELETE FROM 7_MATKUL
WHERE NAMA = 'MOTIVASI USAHA' //TIDAK DIJALANKAN DALAM DB ORACLE

//MENGHAPUS DATA DENGAN KONDISI ALAMAT
DELETE FROM 7_MATKUL
WHERE SKS = '4' //TIDAK DIJALANKAN DALAM DB ORACLE

/MENGHAPUS DATA DENGAN KONDISI NOHP
DELETE FROM 7_MATKUL 
WHERE FAKULTAS = 'ILMU KOMPUTER'  //TIDAK DIJALANKAN DALAM DB ORACLE 
